General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: None
    gpus: [0]
    epochs: &epoch 200 
    grad_acc: 2
    frozen_bn: False
    patience: 10
    server: train #train #test
    log_path: logs/

Data:
    dataset_name: camel_data
    data_shuffle: False
    data_dir: /home/jonathan/code/CLAM/Rebuttal_MEDIA/features_conch_MEN/pt_files/
    label_dir: /home/jonathan/code/TransMIL/dataset_csv/splits_Men_transmil_format/
    fold: 0
    nfold: 5
    k_start: 5
    k_end: 10

    train_dataloader:
        batch_size: 1 
        num_workers: 4

    test_dataloader:
        batch_size: 1
        num_workers: 4

Model:
    name: TransMIL
    n_classes: 244
    embed_dim: 512



Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

